name: Flutter CI/CD

on:
  push:
    branches: [ main, feature* ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Cache Flutter dependencies
    #   uses: actions/cache@v2
    #   env:
    #     cache-name: cache-flutter-dependencies
    #   with:
    #     path: /opt/hostedtoolcache/flutter
    #     key: ${{ runner.os }}-flutter-${{ env.cache-name }}-${{ hashFiles('**/pubspec.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-flutter-${{ env.cache-name }}-
    #       ${{ runner.os }}-flutter-
    #       ${{ runner.os }}-
          
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'

    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.3'

    - name: Clean build packages
      run: flutter clean

    - name: Install dependencies      
      run: flutter pub get

    # - name: Check for formatting issues
    #   run: flutter format --set-exit-if-changed
    
    - name: Analyze Dart code
      run: flutter analyze

    - name: Run tests
      run: flutter test

    # Note: Integration testing must be properly set up before
    # you can run integration tests.
    # Read more on Flutter integration testing here:
    # https://flutter.dev/docs/testing/integration-tests
    # - name: Run integration tests
    #   run: flutter drive --target=test_driver/app.dart

    # Note: This workflow builds the apk in release mode
    # since the flutter build command defaults to --release.
    # Read more on Flutter build modes here: 
    # https://flutter.dev/docs/testing/build-modes
    # - name: Build release APK
    #   run: flutter build apk --split-per-abi

    # Upload generated apk to the artifacts.
    # - uses: actions/upload-artifact@v1
    #   with:
    #     name: release-apk
    #     path: build/app/outputs/apk/release/app-release.apk

  # release:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Release on GitHub
  #   - uses: actions/checkout@v2
  #     uses: ncipollo/release-action@v1
  #     with:
  #       artifacts: "build/app/outputs/apk/release/*.apk"
  #       token: ${{ secrets.FLUTTER_CICD }}